### ISSUE TITLE
支持react-window-infinite-loader吗？

### ISSUE THREAD

**Issue by snowjujube** [dominicleo/remax-virtual-list#2]
触底的无限加载该怎么办呀（微信小程序）

**Comment by dominicleo** [comment]
支持 react-window-infinite-loader 的

https://remax-virtual-list.now.sh/components/infinite-loader

**Comment by snowjujube** [comment]
> 支持 react-window-infinite-loader 的
> 
> https://remax-virtual-list.now.sh/components/infinite-loader

谢谢🙏
